title: Matthew Sam # your name (or website title) here
logo: "/images/Formal Picture.jpeg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
 
  <a href="https://www.linkedin.com/in/matthew-sam2001/">LinkedIn</a> 
  <br>
  <a href="/pdf/Sam,M,Resume.pdf">Resume</a>  
  <br>
  <a href="https://github.com/mfs323">GitHub</a>  
  <br>

  
theme: jekyll-theme-minimal
